#spring.application.name=boardexam
spring:
  application:
    name: boardexam
  datasource:
    url: jdbc:mysql://localhost:3306/hyejindb
    username: hyejin66
    password: u1234
    driver-class-name: com.mysql.cj.jdbc.Driver
